-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.exercises (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  slug text NOT NULL UNIQUE,
  icon_description text NOT NULL,
  instructions text NOT NULL,
  video_description text NOT NULL,
  equipment_text text NOT NULL,
  equipment_groups jsonb NOT NULL,
  exercise_location ARRAY NOT NULL DEFAULT '{}'::text[],
  rep_limitations_progression_rules text NOT NULL,
  progression_by_client_feedback text NOT NULL,
  pain_injury_protocol text NOT NULL,
  special_rules_by_location text NOT NULL,
  trainer_notes text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  muscle_categories ARRAY,
  CONSTRAINT exercises_pkey PRIMARY KEY (id)
);
CREATE TABLE public.todos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  title text NOT NULL,
  description text,
  completed boolean DEFAULT false,
  user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT todos_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_feedback (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workout_plan_id uuid NOT NULL,
  week_number integer NOT NULL CHECK (week_number >= 1 AND week_number <= 8),
  feedback_text text NOT NULL,
  difficulty_rating integer NOT NULL CHECK (difficulty_rating >= 1 AND difficulty_rating <= 5),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT user_feedback_workout_plan_id_fkey FOREIGN KEY (workout_plan_id) REFERENCES public.workout_plans(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  profile_text text NOT NULL,
  onboarding_answers jsonb NOT NULL DEFAULT '[]'::jsonb,
  onboarding_completed boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.workout_entries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workout_plan_id uuid NOT NULL,
  week_number integer NOT NULL CHECK (week_number >= 1 AND week_number <= 8),
  day_name text NOT NULL,
  day USER-DEFINED NOT NULL,
  date date NOT NULL,
  exercise_id uuid NOT NULL,
  sets integer NOT NULL CHECK (sets > 0),
  reps text NOT NULL,
  weight text,
  time text,
  notes text,
  streak_exercise_id uuid NOT NULL,
  streak_exercise_notes text,
  is_adjusted boolean DEFAULT false,
  adjustment_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  preset_id uuid,
  CONSTRAINT workout_entries_pkey PRIMARY KEY (id),
  CONSTRAINT workout_entries_workout_plan_id_fkey FOREIGN KEY (workout_plan_id) REFERENCES public.workout_plans(id),
  CONSTRAINT workout_entries_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id),
  CONSTRAINT workout_entries_streak_exercise_id_fkey FOREIGN KEY (streak_exercise_id) REFERENCES public.exercises(id),
  CONSTRAINT workout_entries_preset_id_fkey FOREIGN KEY (preset_id) REFERENCES public.workout_presets(id)
);
CREATE TABLE public.workout_entry_alternatives (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workout_entry_id uuid NOT NULL,
  alternative_exercise_id uuid NOT NULL,
  note text,
  position integer NOT NULL CHECK ("position" > 0),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workout_entry_alternatives_pkey PRIMARY KEY (id),
  CONSTRAINT workout_entry_alternatives_workout_entry_id_fkey FOREIGN KEY (workout_entry_id) REFERENCES public.workout_entries(id),
  CONSTRAINT workout_entry_alternatives_alternative_exercise_id_fkey FOREIGN KEY (alternative_exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.workout_entry_exercise_notes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  workout_entry_id uuid NOT NULL,
  exercise_id uuid NOT NULL,
  note text NOT NULL DEFAULT ''::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workout_entry_exercise_notes_pkey PRIMARY KEY (id),
  CONSTRAINT workout_entry_exercise_notes_workout_entry_id_fkey FOREIGN KEY (workout_entry_id) REFERENCES public.workout_entries(id),
  CONSTRAINT workout_entry_exercise_notes_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.workout_plan_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  request_id uuid NOT NULL UNIQUE,
  user_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'processing'::text CHECK (status = ANY (ARRAY['processing'::text, 'completed'::text, 'failed'::text])),
  workout_plan_id uuid,
  user_profile text NOT NULL,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  current_step integer DEFAULT 1,
  total_steps integer DEFAULT 3,
  step_description text DEFAULT 'Generating workout plan...'::text,
  exercises_total integer DEFAULT 0,
  exercises_completed integer DEFAULT 0,
  CONSTRAINT workout_plan_requests_pkey PRIMARY KEY (id),
  CONSTRAINT workout_plan_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT workout_plan_requests_workout_plan_id_fkey FOREIGN KEY (workout_plan_id) REFERENCES public.workout_plans(id)
);
CREATE TABLE public.workout_plans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  summary text NOT NULL,
  start_date date NOT NULL,
  status USER-DEFINED DEFAULT 'active'::workout_plan_status,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workout_plans_pkey PRIMARY KEY (id),
  CONSTRAINT workout_plans_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.workout_preset_entries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  preset_id uuid NOT NULL,
  exercise_id uuid NOT NULL,
  position integer NOT NULL CHECK ("position" > 0),
  sets integer NOT NULL CHECK (sets > 0),
  reps text NOT NULL,
  weight text,
  time text,
  notes text,
  streak_exercise_id uuid,
  streak_exercise_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT workout_preset_entries_pkey PRIMARY KEY (id),
  CONSTRAINT workout_preset_entries_preset_id_fkey FOREIGN KEY (preset_id) REFERENCES public.workout_presets(id),
  CONSTRAINT workout_preset_entries_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id),
  CONSTRAINT workout_preset_entries_streak_exercise_id_fkey FOREIGN KEY (streak_exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.workout_preset_entry_alternatives (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  preset_entry_id uuid NOT NULL,
  alternative_exercise_id uuid NOT NULL,
  note text,
  position integer NOT NULL CHECK ("position" > 0),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT workout_preset_entry_alternatives_pkey PRIMARY KEY (id),
  CONSTRAINT workout_preset_entry_alternatives_preset_entry_id_fkey FOREIGN KEY (preset_entry_id) REFERENCES public.workout_preset_entries(id),
  CONSTRAINT workout_preset_entry_alternatives_alternative_exercise_id_fkey FOREIGN KEY (alternative_exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.workout_presets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text NOT NULL,
  day_name text NOT NULL,
  image_key text,
  difficulty text NOT NULL CHECK (difficulty = ANY (ARRAY['easy'::text, 'medium'::text, 'hard'::text])),
  estimated_duration integer NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT workout_presets_pkey PRIMARY KEY (id)
);
CREATE TABLE public.workout_session_adjustments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['reps'::text, 'weight'::text, 'rest'::text, 'exercise_swap'::text, 'sets'::text])),
  workout_entry_id uuid,
  exercise_id uuid,
  from_value text NOT NULL,
  to_value text NOT NULL,
  reason text NOT NULL,
  affected_set_numbers ARRAY,
  affects_future_sets boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb,
  CONSTRAINT workout_session_adjustments_pkey PRIMARY KEY (id),
  CONSTRAINT workout_session_adjustments_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.workout_sessions(id),
  CONSTRAINT workout_session_adjustments_workout_entry_id_fkey FOREIGN KEY (workout_entry_id) REFERENCES public.workout_entries(id),
  CONSTRAINT workout_session_adjustments_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.workout_session_chat (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id uuid NOT NULL,
  conversation_id text NOT NULL,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['connected'::text, 'disconnected'::text])),
  details text,
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT workout_session_chat_pkey PRIMARY KEY (id),
  CONSTRAINT workout_session_chat_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.workout_sessions(id)
);
CREATE TABLE public.workout_session_sets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id uuid NOT NULL,
  workout_entry_id uuid NOT NULL,
  exercise_id uuid NOT NULL,
  set_number integer NOT NULL,
  target_reps integer,
  target_weight numeric,
  target_time integer,
  actual_reps integer,
  actual_weight numeric,
  actual_time integer,
  difficulty text CHECK (difficulty = ANY (ARRAY['easy'::text, 'medium'::text, 'hard'::text, 'impossible'::text])),
  user_notes text,
  started_at timestamp with time zone,
  completed_at timestamp with time zone NOT NULL DEFAULT now(),
  is_completed boolean DEFAULT true,
  skipped boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  rest_started_at timestamp with time zone,
  rest_completed_at timestamp with time zone,
  rest_duration_seconds integer,
  rest_extended boolean DEFAULT false,
  pause_time_ms bigint DEFAULT 0,
  CONSTRAINT workout_session_sets_pkey PRIMARY KEY (id),
  CONSTRAINT workout_session_sets_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.workout_sessions(id),
  CONSTRAINT workout_session_sets_workout_entry_id_fkey FOREIGN KEY (workout_entry_id) REFERENCES public.workout_entries(id),
  CONSTRAINT workout_session_sets_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(id)
);
CREATE TABLE public.workout_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  workout_plan_id uuid NOT NULL,
  week_number integer NOT NULL,
  day USER-DEFINED NOT NULL,
  day_name text NOT NULL,
  date date NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['selected'::text, 'preparing'::text, 'exercising'::text, 'paused'::text, 'completed'::text, 'finished_early'::text, 'abandoned'::text])),
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  paused_at timestamp with time zone,
  resumed_at timestamp with time zone,
  current_exercise_index integer DEFAULT 0,
  current_set_index integer DEFAULT 0,
  completed_exercises integer DEFAULT 0,
  completed_sets integer DEFAULT 0,
  total_exercises integer NOT NULL,
  total_sets integer NOT NULL,
  total_time_ms bigint DEFAULT 0,
  total_pause_time_ms bigint DEFAULT 0,
  last_activity_at timestamp with time zone DEFAULT now(),
  is_fully_completed boolean DEFAULT false,
  finished_early boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT workout_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT workout_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT workout_sessions_workout_plan_id_fkey FOREIGN KEY (workout_plan_id) REFERENCES public.workout_plans(id)
);