name: EAS Development Build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for'
        required: true
        type: choice
        default: all
        options:
          - all
          - android
          - ios
      profile:
        description: 'Build profile to use'
        required: true
        type: choice
        default: development
        options:
          - development
          - preview
  push:
    branches:
      - master
      - main
      - development
      - dev
  pull_request:
    branches:
      - master
      - main
      - development

jobs:
  build:
    name: EAS Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Verify EAS project
        run: eas whoami

      - name: Set build variables
        run: |
          echo "PLATFORM=${{ github.event.inputs.platform || 'all' }}" >> $GITHUB_ENV
          echo "PROFILE=${{ github.event.inputs.profile || 'development' }}" >> $GITHUB_ENV

      - name: Create development build
        run: |
          eas build \
            --platform $PLATFORM \
            --profile $PROFILE \
            --non-interactive \
            --no-wait

      - name: Comment on PR with build info
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const { data: builds } = await github.rest.repos.listCommitStatusesForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha
            });
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Development build started!**
              
              Platform: \`${{ env.PLATFORM }}\`
              Profile: \`${{ env.PROFILE }}\`
              
              You can monitor the build progress on the [EAS dashboard](https://expo.dev).
              
              Once complete, the build will be available for internal distribution.`
            }); 