name: EAS Update

on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Update channel'
        required: true
        type: choice
        default: preview
        options:
          - development
          - preview
          - production
  push:
    branches:
      - master
      - main
      - development
      - dev
  pull_request:
    branches:
      - master
      - main
      - development

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Determine update channel
        id: channel
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "channel=${{ github.event.inputs.channel }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/main" ] || [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "channel=production" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/development" ] || [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "channel=development" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "channel=preview" >> $GITHUB_OUTPUT
          else
            echo "channel=preview" >> $GITHUB_OUTPUT
          fi

      - name: Create update
        if: github.event_name != 'pull_request'
        run: |
          eas update \
            --channel ${{ steps.channel.outputs.channel }} \
            --message "Update from ${{ github.ref_name }} - ${{ github.event.head_commit.message || github.event.commits[0].message }}" \
            --non-interactive

      - name: Create preview update for PR
        if: github.event_name == 'pull_request'
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto

      - name: Comment on PR with update info
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **EAS Update Published!**
              
              Channel: \`${{ steps.channel.outputs.channel }}\`
              Branch: \`${{ github.ref_name }}\`
              
              The update has been published and will be available to compatible builds on this channel.
              
              You can view the update on the [EAS dashboard](https://expo.dev).`
            }); 